### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '<float>'

### ISSUE THREAD

**Issue by sntsris** [hnmr293/sd-webui-llul#1]
Thx for making a nice ext! However, moving the gray box does not seem to work. Is this a bug?

**Env**
python: 3.9.16
torch: 1.13.1+cu117
xformers: 0.0.14.dev
gradio: 3.16.2 
commit: [0cc0ee1b](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8)

**Error**
```
Error running process: /storage/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-llul/scripts/llul.py
Traceback (most recent call last):
  File "/storage/stable-diffusion/stable-diffusion-webui/modules/scripts.py", line 386, in process
    script.process(p, *script_args)
  File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-llul/scripts/llul.py", line 154, in process
    x=int(x) / p.width,
ValueError: invalid literal for int() with base 10: '123.55087280273438'
```

**Comment by hnmr293** [comment]
Thank you for your feedback, sntsris!
This is a bug.
I've fixed it. Please update and try it.
