### ISSUE TITLE
Could you add "select upscale model" options?

### ISSUE THREAD

**Issue by jasonmatobo** [hnmr293/sd-webui-llul#12]
I'm not sure if my understanding is right
This extension is using  default  Latent model to upscale specific area
But can you add an options that user can select different model (or upscale method)?
Like Hires. fix can let user select model from "stable-diffusion-webui\models\ESRGAN"

**Comment by hnmr293** [comment]
Since LLuL operates the latent space of stable diffusion, the usual super-resolution model cannot be used.
(Note that Hires. fix other than "latent" types are just image-postprocessing.)
