### ISSUE TITLE
import image as reference

### ISSUE THREAD

**Issue by Kepler-16b** [hnmr293/sd-webui-llul#13]
As title says, can you make it so that we can drag image into the canvas, like controlnet do? For better visual reference.

**Comment by Woisek** [comment]
I second that heavily! As it is now, it has no real use because now we can only guess, where we set the box. The smaller the box, the clearer this becomes. A way bigger preview with the current generated image would definately help a lot.

**Comment by Cyan101** [comment]
Perhaps an extension to the "send to extras" to send the current image to this tool, would be very nice though

**Comment by QR-0W** [comment]
Yes. This is an important function
