### ISSUE TITLE
incompatibility with controlnet extension (GRadio buttons)

### ISSUE THREAD

**Issue by freecoderai01** [hnmr293/sd-webui-llul#15]
[sd-webui-llul](https://github.com/hnmr293/sd-webui-llul) issues value to [controlnet extension](https://github.com/Mikubill/sd-webui-controlnet/), while it should not, breaking controlnet in img2img mode.
Problem may be in this part of code that deals with gradio buttons:
https://github.com/hnmr293/sd-webui-llul/blob/master/scripts/llul.py#L30-L50

https://github.com/Mikubill/sd-webui-controlnet/issues/598
![2023-03-15-151730_936x155_scrot](https://user-images.githubusercontent.com/126322810/225356169-912c9b4d-fe4e-4b68-aeb3-79d7c8d5d4f4.png)
![2023-03-15-151713_1241x196_scrot](https://user-images.githubusercontent.com/126322810/225356296-37425e4b-a51b-427b-95a3-850b2fe9c8fc.png)

**Comment by hnmr293** [comment]
Thanks for your feedback.
I think this issue has been fixed.
