### ISSUE TITLE
[Feature] Add X Y positions on screen

### ISSUE THREAD

**Issue by Fllamber** [hnmr293/sd-webui-llul#18]
Could you add the position of each side of the square or rectangle that appears inside the canvas? That position could also be saved as generation info as it also changes how the image is composed.

**Comment by hnmr293** [comment]
I have made updates for the position issue.
See https://github.com/hnmr293/sd-webui-llul/issues/25#issuecomment-1532342577

If you have any questions, please reopen this issue.
