### ISSUE TITLE
Selection box disappears when minimizing menu

### ISSUE THREAD

**Issue by erasels** [hnmr293/sd-webui-llul#19]
Hello, first off I'm on the newest Auromatic1111 version and downloaded this extension yesterday. I am on Windows 10.

The issue:
As described in the title, the selection boss you can drag around to select the area for enriching the detail disappears if you close the menu (by clicking on the LLuL header) and then reopen it. It cannot be recovered until the UI is reloaded. It works in both txt2img and img2img.

Before:
![Before](https://user-images.githubusercontent.com/20698806/228339691-0eb7cc5a-2536-45c4-9fa1-d83b3c034961.png)
After:
![After](https://user-images.githubusercontent.com/20698806/228339759-c6b8c222-c647-4a34-bec4-b72b56063dac.png)

**Comment by hnmr293** [comment]
Thanks for your feedback.
I've fixed. Please update LLuL and try it again.

**Comment by phamhungd** [comment]
@hnmr293 Unfortunately, after fixing the above error, llul on my colab version has such an error, hope you can restore :((
<img width="1040" alt="Ảnh màn hình 2023-04-01 lúc 18 43 42" src="https://user-images.githubusercontent.com/39170814/229286715-8af6f3e4-fd9d-4bc8-8c91-cba8d34413b1.png">

**Comment by erasels** [comment]
The Box still also disappears if you move the targeted area and then minimize/reopen

**Comment by hnmr293** [comment]
@erasels 
Sorry again. I've fixed it.
It was due to gradio update.
Note: Once the accordion is closed, all settings will be gone. It is due to the current gradio's implementation. Sorry!

@phamhungd
Please let me know your environment.
![image](https://user-images.githubusercontent.com/120772120/229290186-acd13214-c474-46c7-8481-103aae0c1977.png)

**Comment by phamhungd** [comment]
maybe i use a rather old version
<img width="736" alt="Ảnh màn hình 2023-04-01 lúc 20 03 40" src="https://user-images.githubusercontent.com/39170814/229290636-690f2b47-a921-4048-9c35-8cc34aecd1c4.png">
