### ISSUE TITLE
the llul extension links to posex and not to this

### ISSUE THREAD

**Issue by gsgoldma** [hnmr293/sd-webui-llul#2]
woops

**Comment by hnmr293** [comment]
I need more information.
Please tell me the problem what you have encountered.

**Comment by gsgoldma** [comment]
if you're trying to install this from inside auto1111 extension tab, it will link to your other extension for poseX, it will not install this extension

**Comment by hnmr293** [comment]
It seems very strange. In my environment, I can successfully install this extension from WebUI `Extensions` tab.
Please check your input URL and `Local directory name` again.

![image](https://user-images.githubusercontent.com/120772120/222923920-bd7e60f3-31ba-4a69-bf89-2cb376754e86.png)

*Before:*

![image](https://user-images.githubusercontent.com/120772120/222923877-9b27de29-735f-4700-a913-f77991ffdc45.png)

*After:*

![image](https://user-images.githubusercontent.com/120772120/222923967-ce3e650c-b327-475e-80cc-5a695a2c4edc.png)

**Comment by taylorhand** [comment]
> I need more information. Please tell me the problem what you have encountered.

The extension index AUTO1111 pulls for listing available extensions to install has the wrong URL currently:

![image](https://user-images.githubusercontent.com/82241809/222932680-71d52015-3f84-4ffe-a61f-9ee779c7ff53.png)

It works fine if you manually install it using the 'install from URL' option.

**Comment by catboxanon** [comment]
This really shouldn't be reported here, the extension index is managed in the webui repo.

cc @ClashSAN

**Comment by hnmr293** [comment]
It seems to have been fixed.
