### ISSUE TITLE
Sorry, I cannot see the gray box

### ISSUE THREAD

**Issue by YondSun** [hnmr293/sd-webui-llul#22]
![image](https://user-images.githubusercontent.com/22810091/229304683-435527fb-0e51-4614-9816-b451c03494dc.png)
Sorry, I cannot see the gray box you mentioned. Is it related to my Pytorch version update or the use of SDP?
![image](https://user-images.githubusercontent.com/22810091/229304692-f9d28d57-6bac-426b-bc66-40a5e2618bc0.png)

**Comment by YondSun** [comment]
![image](https://user-images.githubusercontent.com/22810091/229307704-af2a2f16-2dce-40f0-9064-81d688a04c8e.png)
still have the problem

**Comment by YondSun** [comment]
WebUI version:2023Week8

**Comment by zejacky** [comment]
Same problem here. After the update to 6c8a27fd (Fri Mar 31 19:16:41 2023).
Version b20337ae (Wed Mar 22 15:56:08 2023) was ok.

Or its not necessary to use the box anymore?

Thank you very much.

**Comment by zejacky** [comment]
> Same problem here. After the update to 6c8a27fd (Fri Mar 31 19:16:41 2023). Version [b20337a](https://github.com/hnmr293/sd-webui-llul/commit/b20337ae1091ea65fdaf7108a2eaac13fed078d5) (Wed Mar 22 15:56:08 2023) was ok.
> 
> Or its not necessary to use the box anymore?
> 
> Thank you very much.



> WebUI version:2023Week8

I solved the problem by updating A1111 to the latest commit (git pull). Bevore I was using gradio 3.16.2 now 3.23.0. However beware. gradio 3.23.0 is very buggy. (commit 22bcc7be428c94e9408f589966c2040187245d81)

**Comment by wwb1988217** [comment]
> ![图像](https://user-images.githubusercontent.com/22810091/229304683-435527fb-0e51-4614-9816-b451c03494dc.png) 对不起，我看不到你提到的灰色框。是不是和我的Pytorch版本更新或者SDP的使用有关？ ![图像](https://user-images.githubusercontent.com/22810091/229304692-f9d28d57-6bac-426b-bc66-40a5e2618bc0.png)

我和你问题一样，如何解决？

**Comment by gotoolkits** [comment]
I'm having the same problem, how do I go about fixing it?

**Comment by Lamaluo** [comment]
me too

**Comment by TUNAN996** [comment]
有人解决这个问题了吗？是怎么解决的可以分享一下吗

**Comment by mufiku** [comment]
> 有人解决这个问题了吗？是怎么解决的可以分享一下吗

Have you tried restarting A1111?

The grey box are on the lower part of the UI. 

Generate an image using specific seed.
Then send the generated image to img2img and follow these below.

Resolution used: 448,768

Sampling method: Euler A
Sampling steps: 20
CFG scale: 10
Denoising strength: 0.3

Tick the enable button right after image sent to img2img

Multiplication (2^N): 1
Weight: 0.5

Script
X/Y/Z plot
X type: LLuL Enabled
X values
false, true (click yellow button on the right)
Tick Draw legend or other box if needed

Hit generate. See the comparison.

If you're using a RTX 2 series, try to lower the resolution, you can go higher if you're using RTX 3 or 4 series. The result will get better.

**Comment by wwb1988217** [comment]
> > 有人解决这个问题了吗？是怎么解决的可以分享一下吗
> 
> Have you tried restarting A1111?
> 
> The grey box are on the lower part of the UI.
> 
> Generate an image using specific seed. Then send the generated image to img2img and follow these below.
> 
> Resolution used: 448,768
> 
> Sampling method: Euler A Sampling steps: 20 CFG scale: 10 Denoising strength: 0.3
> 
> Tick the enable button right after image sent to img2img
> 
> Multiplication (2^N): 1 Weight: 0.5
> 
> Script X/Y/Z plot X type: LLuL Enabled X values false, true (click yellow button on the right) Tick Draw legend or other box if needed
> 
> Hit generate. See the comparison.
> 
> If you're using a RTX 2 series, try to lower the resolution, you can go higher if you're using RTX 3 or 4 series. The result will get better.

No, I restarted the webui, and I still can't see the gray box

**Comment by mufiku** [comment]
> > > 有人解决这个问题了吗？是怎么解决的可以分享一下吗
> > 
> > 
> > Have you tried restarting A1111?
> > The grey box are on the lower part of the UI.
> > Generate an image using specific seed. Then send the generated image to img2img and follow these below.
> > Resolution used: 448,768
> > Sampling method: Euler A Sampling steps: 20 CFG scale: 10 Denoising strength: 0.3
> > Tick the enable button right after image sent to img2img
> > Multiplication (2^N): 1 Weight: 0.5
> > Script X/Y/Z plot X type: LLuL Enabled X values false, true (click yellow button on the right) Tick Draw legend or other box if needed
> > Hit generate. See the comparison.
> > If you're using a RTX 2 series, try to lower the resolution, you can go higher if you're using RTX 3 or 4 series. The result will get better.
> 
> No, I restarted the webui, and I still can't see the gray box

The grey box as at the bottom, on the "LLuL"

**Comment by TUNAN996** [comment]
> > 有人解决这个问题了吗？是怎么解决的可以分享一下吗
> 
> Have you tried restarting A1111?
> 
> The grey box are on the lower part of the UI.
> 
> Generate an image using specific seed. Then send the generated image to img2img and follow these below.
> 
> Resolution used: 448,768
> 
> Sampling method: Euler A Sampling steps: 20 CFG scale: 10 Denoising strength: 0.3
> 
> Tick the enable button right after image sent to img2img
> 
> Multiplication (2^N): 1 Weight: 0.5
> 
> Script X/Y/Z plot X type: LLuL Enabled X values false, true (click yellow button on the right) Tick Draw legend or other box if needed
> 
> Hit generate. See the comparison.
> 
> If you're using a RTX 2 series, try to lower the resolution, you can go higher if you're using RTX 3 or 4 series. The result will get better.

我这就去尝试一下，非常感谢你的解答，我想主要原因可能还是版本低

**Comment by lfuu** [comment]
same problem

**Comment by linzzzzllll** [comment]
我也是

**Comment by Kotyar7878** [comment]
> > Same problem here. After the update to 6c8a27fd (Fri Mar 31 19:16:41 2023). Version [b20337a](https://github.com/hnmr293/sd-webui-llul/commit/b20337ae1091ea65fdaf7108a2eaac13fed078d5) (Wed Mar 22 15:56:08 2023) was ok.
> > Or its not necessary to use the box anymore?
> > Thank you very much.
> 
> > WebUI version:2023Week8
> 
> I solved the problem by updating A1111 to the latest commit (git pull). Bevore I was using gradio 3.16.2 now 3.23.0. However beware. gradio 3.23.0 is very buggy. (commit 22bcc7be428c94e9408f589966c2040187245d81)

I can't find the version b20337a you mentioned, 3.23.0 has many bugs, is it worth downloading

**Comment by Kotyar7878** [comment]
> > > 有人解决这个问题了吗？是怎么解决的可以分享一下吗
> > 
> > 
> > Have you tried restarting A1111?
> > The grey box are on the lower part of the UI.
> > Generate an image using specific seed. Then send the generated image to img2img and follow these below.
> > Resolution used: 448,768
> > Sampling method: Euler A Sampling steps: 20 CFG scale: 10 Denoising strength: 0.3
> > Tick the enable button right after image sent to img2img
> > Multiplication (2^N): 1 Weight: 0.5
> > Script X/Y/Z plot X type: LLuL Enabled X values false, true (click yellow button on the right) Tick Draw legend or other box if needed
> > Hit generate. See the comparison.
> > If you're using a RTX 2 series, try to lower the resolution, you can go higher if you're using RTX 3 or 4 series. The result will get better.
> 
> 我这就去尝试一下，非常感谢你的解答，我想主要原因可能还是版本低

How is the effect

**Comment by wwb1988217** [comment]
> 

听说最新版的webui可以正常使用这个插件，但是最新版的webui图库浏览器会读取不出来图片信息，所以我还是先不升级了，等新版稳定了再升级吧

**Comment by eintr** [comment]
Same problem. DuckduckGo security plugin disabled already.

**Comment by Jascyc** [comment]
I have the same issue after updated WEBUI to 1.2.1 2 days ago.
![Screencap](https://github.com/hnmr293/sd-webui-llul/assets/132324700/31f1a157-ac59-4236-9158-66e50a8ef836)

**Comment by Alyndiar** [comment]
Same problem. Since I updated WebUI the last time, no more mask/background display in LLuL

**Comment by tartarengia** [comment]
Same here, no more gray box with A1111 V1.21 and Gradio 3.29.0
