### ISSUE TITLE
Coordinates, AR and Size

### ISSUE THREAD

**Issue by hazmatai7** [hnmr293/sd-webui-llul#25]
Love this ext. Is it possible to add:
- coordinates for exact regeneration?
- aspect ratio for more precise localized upscale?
- size or percent of box?

cheers!

**Comment by hnmr293** [comment]
I have made updates related to this issue.

- add mask (please see README.md and below examples)
- add x/y input area (see image below)

You can use mask for changing actual aspect ratio and sizing.

* upper left is enabled
![image](https://user-images.githubusercontent.com/120772120/235816379-6812d9ad-c523-47bf-bd13-83ccc35c817e.png)

* 16:9 aspect ratio
![image](https://user-images.githubusercontent.com/120772120/235816515-4f54d45f-40e7-4f70-974c-f5dc6b35cdc9.png)

* screenshot of x/y input box
![image](https://user-images.githubusercontent.com/120772120/235816142-b4b40aca-96e6-4f96-af37-a9a3cb09f612.png)

If you have any questions, please reopen this issue.
