### ISSUE TITLE
Can make the gray box appear on the generated image?

### ISSUE THREAD

**Issue by pimin12** [hnmr293/sd-webui-llul#26]
Now I have to guess if the gray box is where I want it

**Comment by hnmr293** [comment]
I've updated.
Please update llul and try it.
You can see an additional checkbox below the canvas.

![image](https://user-images.githubusercontent.com/120772120/236263006-45c3d7b5-2d8c-4d1a-b108-826ea58088b0.png)

If you enable this checkbox, you can retrieve effective area of llul like this:

![image](https://user-images.githubusercontent.com/120772120/236262824-08e798f7-d119-490c-aba9-769d2c8f0159.png)

If you have any questions, please reopen this issue.
Thank you!

**Comment by pimin12** [comment]
> I've updated. Please update llul and try it. You can see an additional checkbox below the canvas.
> 
> ![image](https://user-images.githubusercontent.com/120772120/236263006-45c3d7b5-2d8c-4d1a-b108-826ea58088b0.png)
> 
> If you enable this checkbox, you can retrieve effective area of llul like this:
> 
> ![image](https://user-images.githubusercontent.com/120772120/236262824-08e798f7-d119-490c-aba9-769d2c8f0159.png)
> 
> If you have any questions, please reopen this issue. Thank you!

emm still some question,I can't load BG,click that button does not respond,
turn on“Add the effective area to output images.‘’ also not respond
