### ISSUE TITLE
would you please describe in detail the process of implementing this plugin?

### ISSUE THREAD

**Issue by jaycecd** [hnmr293/sd-webui-llul#28]
![image](https://github.com/hnmr293/sd-webui-llul/assets/33342388/283d9497-7c87-40b6-8ada-96a4582d0b90)
Impressive work, but there are some details I don't understand very well, can you explain the implementation process in detail in readme.md? In particular, what is this W?

**Comment by hnmr293** [comment]
Sorry for the delay in replying.
`W` in that figure indicates the layer in your model.
Target layer(s) are displayed in the position shown in the following figure.
(please check `I know what I am doing.` checkbox.)
![image](https://github.com/hnmr293/sd-webui-llul/assets/120772120/70983d03-b8b1-4b6d-9252-f674ebba5ffe)

**Comment by jaycecd** [comment]
I apologize for not seeing your reply until now.
Is `W` the first letter of "weight"? It's a little different from "layer" and a little confusing.
