### ISSUE TITLE
Size must be multiple of 64

### ISSUE THREAD

**Issue by AndreyRGW** [hnmr293/sd-webui-llul#3]
```
Error running process: F:\WBC\sdwb\extensions\sd-webui-llul\scripts\llul.py
Traceback (most recent call last):
  File "F:\WBC\sdwb\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "F:\WBC\sdwb\extensions\sd-webui-llul\scripts\llul.py", line 112, in process
    raise ValueError(f'Image size must be multiple of 64 for LLuL, but {p.width}x{p.height}.')
ValueError: Image size must be multiple of 64 for LLuL, but 608x448.
```

So, it's not possible to use LLuL with an image size that's not a multiple of 64?

upd1: Please, if you know how to fix this, I would appreciate it. If it can't be fixed, how do I apply llul to images whose resolutions are not a multiple of 64? Inpainting?

**Comment by hnmr293** [comment]
Currently it seems there are no problems to do it, so I have fixed it.
Thank you!
