### ISSUE TITLE
No selection grey box? 

### ISSUE THREAD

**Issue by darrenthe** [hnmr293/sd-webui-llul#31]
No selection **grey box?** 
only tick box

![238320253-31f1a157-ac59-4236-9158-66e50a8ef836](https://github.com/hnmr293/sd-webui-llul/assets/48902148/62329aab-d91d-4b6c-a6d3-9bcede92f62f)

**Comment by StanislawKarnacky** [comment]
Same issue after updating auto 1111. No grey box.

**Comment by linzzzzllll** [comment]
Same issue after updating auto 1111. No grey box.

**Comment by Jascyc** [comment]
Same issue after updated WebUI to 1.2.1 a week ago

**Comment by j2l** [comment]
Same here.
Only 
```
cd sd-webui-llul
git reset --hard https://github.com/hnmr293/sd-webui-llul/commit/631059c5787faa62dc6a6efe762ebc2b4b5b04d7
```
make it appear again. From https://github.com/hnmr293/sd-webui-llul/issues/33

**Comment by Nuullll** [comment]
Proposed a PR: https://github.com/hnmr293/sd-webui-llul/pull/34
