### ISSUE TITLE
new mask feature

### ISSUE THREAD

**Issue by ElenViolet** [hnmr293/sd-webui-llul#36]
A long time ago when I used this, when there was no loading of mask pictures yet, everything was fine, you could choose the location of the interaction (for example, the very top of the picture or the very bottom), but now it is always in the middle, even if you load a mask picture where the white one is only up, it will be somewhere in the middle, and never at the top of the image. I changed the resolution of the mask, made it the same size as the picture, made it square, big and small and nothing helps... it's just always in the middle

![Screenshot_9](https://github.com/hnmr293/sd-webui-llul/assets/77670797/7d512f4c-6364-46e4-ae60-3a0fd1a3ab7f)
![Screenshot_10](https://github.com/hnmr293/sd-webui-llul/assets/77670797/b997817c-616d-4631-a919-a2ab6f697657)
![Screenshot_11](https://github.com/hnmr293/sd-webui-llul/assets/77670797/ba75635b-4354-4200-857e-2f8a86c54538)
![Screenshot_12](https://github.com/hnmr293/sd-webui-llul/assets/77670797/daab2cff-2ba0-44d9-92d7-3bf63c7b1ffd)

**Comment by Davis1216** [comment]
mee to

**Comment by akkoxe** [comment]
the same problem

**Comment by hnmr293** [comment]
Thank you for your feedbacks.
I think It has beein fixed in a recent update.
Please update LLuL and try it again.
