### ISSUE TITLE
Positioning problem with resolution other than 512x512

### ISSUE THREAD

**Issue by lyuro** [hnmr293/sd-webui-llul#4]
I have a problem with the positioning of the resolution other than 512x512. For example, I use 1024x1024 to generate an image, and put the locator in the lower right corner. The positioning is in the center. If I am using the method incorrectly, please point it out. Thank you.
![317B5W553W~XGQ7E(7CIWVJ](https://user-images.githubusercontent.com/38397800/223385718-e0bad0a2-e2db-42b3-a9a8-68b8f93c9429.png)

**Comment by hnmr293** [comment]
The correct behavior is that the canvas size changes automatically when the image size is changed. But it doesn't.
Maybe there are some errors of javascript.
Any errors in your Devtools' console (`F12`)?

**Comment by lyuro** [comment]
Oh, I checked it out as prompted.
Yes when I change the resolution an error occurs:
![image](https://user-images.githubusercontent.com/38397800/223746278-e55b542b-100a-45ea-810f-6c110ae3ed2a.png)

![image](https://user-images.githubusercontent.com/38397800/223746120-efde0e20-b4c3-4066-b142-4bf204eafd97.png)

![image](https://user-images.githubusercontent.com/38397800/223750053-d28227d8-ebb1-496c-81ad-6066b7b11b77.png)

**Comment by hnmr293** [comment]
thanks,
and, please tell me what your OS and browser is.
sorry for the additional request.

**Comment by lyuro** [comment]
Sorry for the lack of information I provided, this should be my first time submitting an issue in Git, I haven't developed the habit of collecting environment information

OS: Win10
Browser: Google Chrome 111.0.5563.65 (x64) / Edge 110.0.1587.63 (x64)
WebUI:
python: 3.10.6  
torch: 1.13.1+cu117  
xformers: 0.0.17.dev464  
gradio: 3.16.2  
commit: 0cc0ee1b

**Comment by hnmr293** [comment]
Thanks, lyuro!
Perhaps you are using sliders to set width and height?
If so, for workaround, input width and height in the textboxes, not sliders.
Right now LLuL is not responding to the sliders. I will fix it soon.

**Comment by lyuro** [comment]
That's right!!  I'm used to using sliders, just tried to respond successfully with input values
