### ISSUE TITLE
Runtime error with  "lerp_kernel_scalar" not implemented for 'Half'

### ISSUE THREAD

**Issue by script-money** [hnmr293/sd-webui-llul#6]
Show error on M2 pro, pytorch, I use `--upcast-sampling --opt-sub-quad-attention --use-cpu interrogate` and torch==2.0.0.dev20230131
```
Error completing request████████████████████▋                                               | 4/12 [00:01<00:03,  2.29it/s]
Arguments: ('task(cmmoguzralnnpel)', '', '', ['OL'], 12, 2, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.45, 2, 'R-ESRGAN 4x+', 8, 0, 0, [], 0, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 1, False, True, 1, 0.15, False, 'OUT', ['OUT'], 5, 0, 'Bilinear', False, 'Pooling Max', False, 'Lerp', '123.7265625', '246.2578125', False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
...
File "~/Projects/stable-diffusion-webui/extensions/sd-webui-llul/scripts/llul_hooker.py", line 82, in lerp
    return torch.lerp(v0, v1, t)
RuntimeError: "lerp_kernel_scalar" not implemented for 'Half'
```

**Comment by hnmr293** [comment]
Thank you for your feedback.
I've tried to fix it, but I don't have M2 pro.
So please let me know if your problem has been fixed.

**Comment by script-money** [comment]
> Thank you for your feedback. I've tried to fix it, but I don't have M2 pro. So please let me know if your problem has been fixed.

It's working, thanks

**Comment by ocpinfo** [comment]
> > Thank you for your feedback. I've tried to fix it, but I don't have M2 pro. So please let me know if your problem has been fixed.
> 
> It's working, thanks

Would you please kindly tell me how to fix it? I got the same error:
RuntimeError: "lerp_kernel_scalar" not implemented for 'Half'

**Comment by JoeD016** [comment]
> 

having same issue here, how did you fix it?

**Comment by hnmr293** [comment]
Please enable this checkbox.
![image](https://user-images.githubusercontent.com/120772120/229267743-e9ace156-77cb-42be-8ef3-5e5093535b93.png)

**Comment by Aypixl** [comment]
Hi, sorry to re activate this, but this is the only trace of this error that I can find anywhere, using SD on AMD using directML, all is fine bar Inpainting, i get the same "lerp_kernel_scalar" not implemented for 'Half'. 

I am not using llul so sorry to ask here, i know its a longshot

**Comment by GitIvo** [comment]
Aypixl    Hi, sorry to re activate this, but this is the only trace of this error that I can find anywhere, using SD on AMD using directML, all is fine bar Inpainting, i get the same "lerp_kernel_scalar" not implemented for 'Half'.    

I just put    --no-half      in  webui-user.bat .  And works.
set COMMANDLINE_ARGS=--autolaunch  --no-half
