### ISSUE TITLE
Would it be possible to allow resizing the box?

### ISSUE THREAD

**Issue by jwvanderbeck** [hnmr293/sd-webui-llul#7]
Trying to figure this thing out.  As a side note some docs might be helpful for all the advanced knobs.

That said, on main thing stopping me from using this more is the size of the box is often either too big or too small for what I want to do.  Would it be possible to allow both moving AND scaling the box?

**Comment by poisenbery** [comment]
I was messing around with it and I believe that the Multiplication (2^N) setting changes the size of the box

**Comment by jwvanderbeck** [comment]
Well now I feel like an idiot.  Though I was hoping for a more direct resizing this works.

**Comment by matrix4767** [comment]
That's because the multiplication setting _didn't_ change the size of the box for a while.

**Comment by micky2be** [comment]
Could we also change the ratio? What I want more details on is not always the same shape as the main image
